### PR TITLE
Support for `qs.parse` options (+ `qs` update)

### LINKED ISSUE #18: Support for `qs.parse` options
`qs.parse(..., options)` supports 2nd parameter `options`. It may be useful for example fo a custom `decoder` option. Here is the PR for it (including updating the `qs` version).

### PR DESCRIPTION
**Pull request by Ajaxy**
Resolve #18

### CODE REVIEW

**Comment by fl0w** [comment]
I'd remove the version [bump commit](https://github.com/koajs/qs/pull/19/commits/543c60300ce9fb78dd840cedf73c71df8d414060).

Otherwise LGTM.

**Comment by neolectron** [comment]
any updates on this ?

**Comment by Ajaxy** [comment]
> I'd remove the version bump commit.

Done

> Edit: To really be nitty, I would prefer version bumps for qs and devDeps to be on a separate commit, but that's subjective.

Done

**Comment by niftylettuce** [comment]
Closed in favor #27

**Comment by niftylettuce** [comment]
released to npm as v3.0.0

https://github.com/koajs/qs/releases/tag/v3.0.0

**Pull request closed without merging**
